name: FortuneCookieAPI
on: workflow_dispatch

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Testing workflow
        uses: actions/checkout@v4

      - name: Configurar Java 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '22' 
          cache: maven

      - name: Maven test
        run: mvn test
      
      - name: Checkstyle
        run: mvn checkstyle:checkstyle
