name: FortuneCookieAPI
on: workflow_dispatch

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Testing workflow
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '21' # Altere para '22' se necessário
          cache: maven

      - name: Maven test
        run: mvn test -X
      
      - name: Checkstyle
        run: mvn checkstyle:checkstyle
